### ISSUE TITLE
FinaliseDlg writes wrong value to Settings.FUpdateInterval

### ISSUE THREAD

**Issue by kalwados** [DGH2112/IDE-Fonts#1]
DGHIDEFonts.WindowDlg.pas:

The current implementation of TfrmWindowDlg.FinaliseDlg() stores the value of udFontSize.Position into Settings.FUpdateInterval. That is a bug. That line should be
`  Settings.FUpdateInterval := udDelayInterval.Position;`

See attached patch.
[DGHIDEFonts.WindowDlg.pas.patch.zip](https://github.com/DGH2112/IDE-Fonts/files/2216992/DGHIDEFonts.WindowDlg.pas.patch.zip)

**Comment by DGH2112** [comment]
Yes, that's a classic copy and paste bug, sorry. I'll see if I can get it fixed before the end of the day.
regards
Dave.

**Comment by DGH2112** [comment]
I've just release a new build (1.1a) on GitHub to fix this issue and provide backwards compatibility to D2010. It will take a few more minutes to update the web page.

regards
Dave.
